---
name: Build examples
on:
  - pull_request
  - push
jobs:
  build_esp32_v4_x:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_method:
          - idf
          - make
        branch:
          - master
          - v4.2
        target:
          - esp32
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v2
        with:

          # XXX install python 3.8 because the official python package
          # segfaults when installing modules in the runner.
          #
          # 2020-09-03T02:29:58.2517141Z Successfully installed cffi-1.14.2 cryptography-3.1 future-0.18.2 pycparser-2.20 pyparsing-2.3.1 pyserial-3.4 setuptools-50.1.0 six-1.15.0
          # 2020-09-03T02:30:09.0409148Z /home/runner/work/_temp/66c91304-eef8-456d-84a1-7299428a62f7.sh: line 5:  4140 Segmentation fault      (core dumped) python3 -m pip install --user -r ${IDF_PATH}/requirements.txt
          # 2020-09-03T02:30:09.0414254Z ##[error]Process completed with exit code 139.
          #
          # possibly related issue:
          # https://github.com/actions/virtual-environments/issues/159
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get install \
            bison \
            ccache \
            flex \
            gcc \
            git \
            gperf \
            libffi-dev \
            libncurses-dev \
            libssl-dev \
            make \
            wget

      - name: Set environment variables
        id: set_env
        run: |
          SDK_NAME="esp-idf"
          GCC_PREFIX="xtensa-${{ matrix.target }}-elf"
          GCC_FILE="${GCC_PREFIX}-gcc"
          TOOLCHAIN_DIR="${HOME}/.espressif/tools"
          case "${{ matrix.branch }}" in
          v4.0.2)
            TOOLCHAIN_VERSION="esp-2020r3-8.4.0"
            ;;
          v4.1)
            TOOLCHAIN_VERSION="esp-2020r2-8.2.0"
            ;;
          v4.2-*)
            TOOLCHAIN_VERSION="esp-2020r2-8.2.0"
            ;;
          v4.2|v4.2.*)
            TOOLCHAIN_VERSION="esp-2020r3-8.4.0"
            ;;
          master)
            TOOLCHAIN_VERSION="esp-2020r3-8.4.0"
            ;;
          *)
            echo "Unknown matrix.branch: ${{ matrix.branch }}"
            exit 1
            ;;
          esac
          REPO_DIR=`pwd`
          EXAMPLE_DIR="${REPO_DIR}/examples"
          DISTFILE_DIR="${HOME}/distfiles"
          __PROJECT_PATH=`pwd`

          # XXX actions/checkout does not allow to checkout a repository other
          # than under __PROJECT_PATH
          IDF_PATH="${__PROJECT_PATH}/idf"

          echo "IDF_PATH=${IDF_PATH}" >> ${GITHUB_ENV}
          echo "IDF_TARGET=${{ matrix.target }}" >> ${GITHUB_ENV}

          # cache-idf-tools needs __PROJECT_TOOLCHAIN_DIR
          echo "::set-output name=PROJECT_TOOLCHAIN_DIR::${TOOLCHAIN_DIR}"

          # XXX prefix all the environment variables with `__PROJECT_` to avoid pollution
          echo "__PROJECT_EXAMPLE_DIR=${EXAMPLE_DIR}" >> ${GITHUB_ENV}
          echo "__PROJECT_GCC_FILE=${GCC_FILE}" >> ${GITHUB_ENV}
          echo "__PROJECT_GCC_PREFIX=${GCC_PREFIX}" >> ${GITHUB_ENV}
          echo "__PROJECT_SDK_NAME=${SDK_NAME}" >> ${GITHUB_ENV}
          echo "__PROJECT_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}" >> ${GITHUB_ENV}
          echo "__PROJECT_TOOLCHAIN_DIR=${TOOLCHAIN_DIR}" >> ${GITHUB_ENV}
          echo "__PROJECT_TOOLCHAIN_VERSION=${TOOLCHAIN_VERSION}" >> ${GITHUB_ENV}
          echo "__PROJECT_DISTFILE_DIR=${DISTFILE_DIR}" >> ${GITHUB_ENV}
          echo "__PROJECT_PATH=${__PROJECT_PATH}" >> ${GITHUB_ENV}
          echo "__PROJECT_BUILD_COMMAND=${__PROJECT_BUILD_COMMAND}" >> ${GITHUB_ENV}
          echo "__PROJECT_BUILD_COMMAND_ARG=${__PROJECT_BUILD_COMMAND_ARG}" >> ${GITHUB_ENV}

      - name: Checkout the SDK
        uses: actions/checkout@v2
        with:
          repository: espressif/esp-idf
          path: idf
          submodules: recursive
          ref: ${{ matrix.branch }}

      - name: Fixup the SDK
        run: |

          # XXX workaround removed option, --no-site-packages, from virtualenv. should
          # be removed when the following commit is merged
          # https://github.com/espressif/esp-idf/commit/7a18f02acd7005f7c56e62175a8d1968a1a9019d
          sed -i -e "s/'--no-site-packages',//" ${IDF_PATH}/tools/idf_tools.py

          # XXX remove some modules
          # gdbgui cannot be installed successfully with python 3.8
          sed -i -e "s/^gdbgui.*//" -e "s/^pygdbmi.*//" ${IDF_PATH}/requirements.txt

      - name: Cache esp-idf tools

        # cache esp-idf tools. each tagged branch has fixed versions of tools.
        # the versions do not change. the master is an exception as it is a
        # moving target. do NOT cache tools if the branch is master.
        uses: actions/cache@v2
        id: cache-tools
        if: ${{ matrix.branch != 'master' }}
        with:
          path: ${{ steps.set_env.outputs.PROJECT_TOOLCHAIN_DIR }}
          key: ${{ runner.os }}-${{ matrix.branch }}-${{ matrix.target }}-cache-tools

      - name: Run idf_tools.py install
        if: ${{ steps.cache-tools.outputs.cache-hit != 'true' || matrix.branch == 'master' }}
        run: |
          ${IDF_PATH}/tools/idf_tools.py install

      - name: Run idf_tools.py install-python-env
        run: |
          ${IDF_PATH}/tools/idf_tools.py install-python-env

      - name: Build (idf.py)
        if: ${{ matrix.build_method == 'idf' }}
        run: |
          . ${IDF_PATH}/export.sh
          export CCACHE_BASEDIR="${__PROJECT_PATH}"
          export CCACHE_NOHASHDIR=true
          cd src
          idf.py --ccache build
          echo "Build with CONFIG_PROJECT_LED_TYPE_ADDRESSABLE_SPI)"
          rm sdkconfig
          echo CONFIG_PROJECT_LED_TYPE_ADDRESSABLE_SPI=y >> sdkconfig.default
          idf.py --ccache build

      - name: Setup ccache (make)

        # XXX ccache needs to be configured here
        # unlike idf.py, esp-idf does nothing to setup ccache for make.
        # IDF_CCACHE_ENABLE does not work either.
        if: ${{ matrix.build_method == 'make' }}
        run: |
          GCC_BIN_DIR="${__PROJECT_TOOLCHAIN_DIR}/${__PROJECT_GCC_PREFIX}/${__PROJECT_TOOLCHAIN_VERSION}/${__PROJECT_GCC_PREFIX}/bin"
          CCACHE_BIN_DIR="${HOME}/ccache_bin"
          mkdir -p "${CCACHE_BIN_DIR}"
          (cd "${CCACHE_BIN_DIR}" && ln -s /usr/bin/ccache "${__PROJECT_GCC_FILE}")
          export PATH="${CCACHE_BIN_DIR}:$PATH:${GCC_BIN_DIR}"
          echo "PATH=${PATH}" >> ${GITHUB_ENV}
          echo "CCACHE_BASEDIR=${__PROJECT_PATH}" >> ${GITHUB_ENV}
          echo "CCACHE_NOHASHDIR=true" >> ${GITHUB_ENV}

      - name: Build (make)
        if: ${{ matrix.build_method == 'make' }}
        run: |

          # make sure gcc is in $PATH
          echo ${PATH}
          ${__PROJECT_GCC_FILE} --version

          IGNORE_FILE="travis-ignore"
          . ${IDF_PATH}/export.sh

          cd src
          make defconfig
          make
          echo "Build with CONFIG_PROJECT_LED_TYPE_ADDRESSABLE_SPI)"
          rm sdkconfig
          echo CONFIG_PROJECT_LED_TYPE_ADDRESSABLE_SPI=y > sdkconfig.default
          make clean
          make defconfig
          make
  build_esp8266:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_method:

          # XXX build examples with make only
          # idf.py in ESP8266 RTOS SDK is broken in many ways.
          - make
        branch:
          - master
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get install \
            bison \
            ccache \
            flex \
            gcc \
            git \
            gperf \
            libffi-dev \
            libncurses-dev \
            libssl-dev \
            make \
            wget

      - name: Set environment variables
        id: set_env
        run: |
          SDK_NAME="ESP8266_RTOS_SDK"
          GCC_PREFIX="xtensa-lx106-elf"
          GCC_FILE="${GCC_PREFIX}-gcc"
          TOOLCHAIN_DIR="${HOME}/esp32"
          TOOLCHAIN_FILE="xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz"
          REPO_DIR=`pwd`
          EXAMPLE_DIR="${REPO_DIR}/examples"
          DISTFILE_DIR="${HOME}/distfiles"
          __PROJECT_PATH=`pwd`

          # XXX actions/checkout does not allow to checkout a repository other
          # than under __PROJECT_PATH
          IDF_PATH="${__PROJECT_PATH}/idf"
          echo "IDF_PATH=${IDF_PATH}" >> ${GITHUB_ENV}

          # cache-idf-tools needs PROJECT_DISTFILE_DIR
          echo "::set-output name=PROJECT_DISTFILE_DIR::${DISTFILE_DIR}"

          # XXX prefix all the environment variables with `__PROJECT_` to avoid pollution
          echo "__PROJECT_EXAMPLE_DIR=${EXAMPLE_DIR}" >> ${GITHUB_ENV}
          echo "__PROJECT_GCC_FILE=${GCC_FILE}" >> ${GITHUB_ENV}
          echo "__PROJECT_GCC_PREFIX=${GCC_PREFIX}" >> ${GITHUB_ENV}
          echo "__PROJECT_SDK_NAME=${SDK_NAME}" >> ${GITHUB_ENV}
          echo "__PROJECT_TOOLCHAIN_DIR=${TOOLCHAIN_DIR}" >> ${GITHUB_ENV}
          echo "__PROJECT_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}" >> ${GITHUB_ENV}
          echo "__PROJECT_DISTFILE_DIR=${DISTFILE_DIR}" >> ${GITHUB_ENV}
          echo "__PROJECT_PATH=${__PROJECT_PATH}" >> ${GITHUB_ENV}
          echo "__PROJECT_BUILD_COMMAND=${__PROJECT_BUILD_COMMAND}" >> ${GITHUB_ENV}
          echo "__PROJECT_BUILD_COMMAND_ARG=${__PROJECT_BUILD_COMMAND_ARG}" >> ${GITHUB_ENV}

      - name: Checkout the SDK
        uses: actions/checkout@v2
        with:
          repository: espressif/ESP8266_RTOS_SDK
          path: idf
          submodules: recursive
          ref: ${{ matrix.branch }}
          # XXX git.eclipse.org does not allow to fetch a commit. fetch all
          # the commits.
          fetch-depth: 0

      - name: Install python requirements (pip)
        if: ${{ ! startsWith(matrix.branch, 'v3.3') }}
        run: |

          # XXX upgrade pyOpenSSL because older pyOpenSSL caused issues in
          # the past. this might not be true anymore.
          python -m pip install --user --upgrade pyOpenSSL
          python -m pip install --user -r ${IDF_PATH}/requirements.txt

      - name: Create __PROJECT_DISTFILE_DIR
        run: |
          mkdir -p "${__PROJECT_DISTFILE_DIR}"

      - name: Cache toolchain
        id: cache-idf-tools
        uses: actions/cache@v2
        with:
          path: ${{ steps.set_env.outputs.PROJECT_DISTFILE_DIR }}
          key: ${{ runner.os }}-${{ matrix.branch }}-esp8266-cache-tools

      - name: Download toolchain if it does not exist
        run: |
          if [ ! -f "${__PROJECT_DISTFILE_DIR}/${__PROJECT_TOOLCHAIN_FILE}" ]; then
            wget -O "${__PROJECT_DISTFILE_DIR}/${__PROJECT_TOOLCHAIN_FILE}" "https://dl.espressif.com/dl/${__PROJECT_TOOLCHAIN_FILE}"
          fi

      - name: Extract the toolchain
        run: |
          mkdir -p "${__PROJECT_TOOLCHAIN_DIR}"
          tar -xz -C "${__PROJECT_TOOLCHAIN_DIR}" -f "${__PROJECT_DISTFILE_DIR}/${__PROJECT_TOOLCHAIN_FILE}"

      - name: Setup ccache
        run: |
          __PROJECT_CCACHE_BIN_DIR="${HOME}/ccache_bin"
          mkdir -p "${__PROJECT_CCACHE_BIN_DIR}"
          (cd "${__PROJECT_CCACHE_BIN_DIR}" && ln -s /usr/bin/ccache "${__PROJECT_GCC_FILE}")
          echo "PATH=${__PROJECT_CCACHE_BIN_DIR}:$PATH:${__PROJECT_TOOLCHAIN_DIR}/${__PROJECT_GCC_PREFIX}/bin" >> ${GITHUB_ENV}
          echo "CCACHE_BASEDIR=${__PROJECT_PATH}" >> ${GITHUB_ENV}
          echo "CCACHE_NOHASHDIR=true" >> ${GITHUB_ENV}

      - name: Build (make)
        if: ${{ matrix.build_method == 'make' }}
        run: |

          # make sure gcc is in $PATH
          echo ${PATH}
          ${__PROJECT_GCC_FILE} --version

          # XXX these does not support ESP8266
          export EXCLUDE_COMPONENTS="max7219 mcp23x17 led_strip led_strip_spi"
          (cd src && make defconfig && make)

  # XXX esp32s2 support was introduced in v4.2. older esp-idf does not install
  # toolchains for esp32s2. thus, you cannot add `esp32s2` target to
  # build_esp32_v4_x.
  #
  # this job can be removed when either one of the followings are met:
  #
  # * GitHub Actions supports "early exit" (successfully exit if a condition is
  #   true).
  # * all branches in build_esp32_v4_x supports esp32s2
  #
  # additionally, esp32s2 build requires idf.py. make is not supported.
  build_esp32s2_v4_x:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_method:
          - idf
        branch:
          - master
          - v4.2-beta1
        target:
          - esp32s2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get install \
            bison \
            ccache \
            flex \
            gcc \
            git \
            gperf \
            libffi-dev \
            libncurses-dev \
            libssl-dev \
            make \
            wget

      - name: Set environment variables
        id: set_env
        run: |
          SDK_NAME="esp-idf"
          GCC_PREFIX="xtensa-${{ matrix.target }}-elf"
          GCC_FILE="${GCC_PREFIX}-gcc"
          TOOLCHAIN_DIR="${HOME}/.espressif/tools"
          case "${{ matrix.branch }}" in
          v4.0.2)
            TOOLCHAIN_VERSION="esp-2020r3-8.4.0"
            ;;
          v4.1)
            TOOLCHAIN_VERSION="esp-2020r2-8.2.0"
            ;;
          v4.2.*|v4.2-*)
            TOOLCHAIN_VERSION="esp-2020r2-8.2.0"
            ;;
          master)
            TOOLCHAIN_VERSION="esp-2020r3-8.4.0"
            ;;
          *)
            echo "Unknown matrix.branch: ${{ matrix.branch }}"
            exit 1
            ;;
          esac
          REPO_DIR=`pwd`
          EXAMPLE_DIR="${REPO_DIR}/examples"
          DISTFILE_DIR="${HOME}/distfiles"
          __PROJECT_PATH=`pwd`

          IDF_PATH="${__PROJECT_PATH}/idf"

          # cache-idf-tools needs __PROJECT_TOOLCHAIN_DIR
          echo "::set-output name=PROJECT_TOOLCHAIN_DIR::${TOOLCHAIN_DIR}"

          echo "IDF_PATH=${IDF_PATH}" >> ${GITHUB_ENV}
          echo "IDF_TARGET=${{ matrix.target }}" >> ${GITHUB_ENV}

          echo "__PROJECT_EXAMPLE_DIR=${EXAMPLE_DIR}" >> ${GITHUB_ENV}
          echo "__PROJECT_GCC_FILE=${GCC_FILE}" >> ${GITHUB_ENV}
          echo "__PROJECT_GCC_PREFIX=${GCC_PREFIX}" >> ${GITHUB_ENV}
          echo "__PROJECT_SDK_NAME=${SDK_NAME}" >> ${GITHUB_ENV}
          echo "__PROJECT_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}" >> ${GITHUB_ENV}
          echo "__PROJECT_TOOLCHAIN_DIR=${TOOLCHAIN_DIR}" >> ${GITHUB_ENV}
          echo "__PROJECT_TOOLCHAIN_VERSION=${TOOLCHAIN_VERSION}" >> ${GITHUB_ENV}
          echo "__PROJECT_DISTFILE_DIR=${DISTFILE_DIR}" >> ${GITHUB_ENV}
          echo "__PROJECT_PATH=${__PROJECT_PATH}" >> ${GITHUB_ENV}
          echo "__PROJECT_BUILD_COMMAND=${__PROJECT_BUILD_COMMAND}" >> ${GITHUB_ENV}
          echo "__PROJECT_BUILD_COMMAND_ARG=${__PROJECT_BUILD_COMMAND_ARG}" >> ${GITHUB_ENV}

      - name: Checkout the SDK
        uses: actions/checkout@v2
        with:
          repository: espressif/esp-idf
          path: idf
          submodules: recursive
          ref: ${{ matrix.branch }}

      - name: Fixup the SDK
        run: |

          sed -i -e "s/'--no-site-packages',//" ${IDF_PATH}/tools/idf_tools.py

          sed -i -e "s/^gdbgui.*//" -e "s/^pygdbmi.*//" ${IDF_PATH}/requirements.txt

      - name: Cache esp-idf tools

        # cache esp-idf tools. each tagged branch has fixed versions of tools.
        # the versions do not change. the master is an exception as it is a
        # moving target. do NOT cache tools if the branch is master.
        uses: actions/cache@v2
        id: cache-tools
        if: ${{ matrix.branch != 'master' }}
        with:
          path: ${{ steps.set_env.outputs.PROJECT_TOOLCHAIN_DIR }}
          key: ${{ runner.os }}-${{ matrix.branch }}-${{ matrix.target }}-cache-tools

      - name: Run idf_tools.py install
        if: ${{ steps.cache-tools.outputs.cache-hit != 'true' || matrix.branch == 'master' }}
        run: |
          ${IDF_PATH}/tools/idf_tools.py install

      - name: Run idf_tools.py install-python-env
        run: |
          ${IDF_PATH}/tools/idf_tools.py install-python-env

      - name: Build (idf.py)
        if: ${{ matrix.build_method == 'idf' }}
        run: |
          . ${IDF_PATH}/export.sh

          export CCACHE_BASEDIR="${__PROJECT_PATH}"
          export CCACHE_NOHASHDIR=true

          cd src
          idf.py set-target esp32s2
          idf.py --ccache build
          echo "Build with CONFIG_PROJECT_LED_TYPE_ADDRESSABLE_SPI)"
          rm sdkconfig
          echo CONFIG_PROJECT_LED_TYPE_ADDRESSABLE_SPI=y > sdkconfig.default
          idf.py --ccache build
